
[[tool.pdm.autoexport]]
filename = "requirements.txt"
without-hashes = "true"


[project]
name = ""
version = ""
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = []
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

